#ifndef SRC_APPLICATION_CONSOLE_RESONANCE_FILTER_HANDLERS_H_
#define SRC_APPLICATION_CONSOLE_RESONANCE_FILTER_HANDLERS_H_

#include "console_handlers.h"

void set_resonance_filter_handlers(TReadLine *rl);

#endif /* SRC_APPLICATION_CONSOLE_RESONANCE_FILTER_HANDLERS_H_ */
