#ifndef MODULE_PARAMETER_H_
#define MODULE_PARAMETER_H_

#include "appdefs.h"

typedef enum
{
	DSP_ADDRESS_PRESET_FULL = 0,
	DSP_ADDRESS_PRESET_VOLUME,
	DSP_ADDRESS_CAB_DATA_PRIMARY,
	DSP_ADDRESS_CAB,
	DSP_ADDRESS_MODULES_ENABLE,
	DSP_ADDRESS_CHORUS,
	DSP_ADDRESS_PHASER,
	DSP_ADDRESS_REVERB,
	DSP_ADDRESS_DELAY,
	DSP_ADDRESS_EQ,
	DSP_ADDRESS_TREMOLO,
	DSP_ADDRESS_AMP,
	DSP_ADDRESS_PROGRAMM_CHANGE,
	DSP_ADDRESS_FLANGER,
	DSP_ADDRESS_TUNER_PROCESS,
	DSP_ADDRESS_IND_SRC,
	DSP_ADDRESS_CAB_DRY_MUTE,
	DSP_ADDRESS_EARLY_REFLECTIONS,
	DSP_ADDRESS_CAB_DATA_SECONDARY,
	DSP_ADDRESS_MASTER = 19,
	DSP_ADDRESS_MASTER_VOLUME_CONTROL = 21,
	DSP_ADDRESS_EQ_BAND = 22,
	DSP_ADDRESS_AMP_TYPE,
	DSP_ADDRESS_DSP_RUN,
	DSP_ADDRESS_SPDIF,
	DSP_ADDRESS_PREAMP,
	DSP_ADDRESS_CAB_CONFIG,
	DSP_ADDRESS_GATE,
	DSP_ADDRESS_COMPRESSOR,
	DSP_ADDRESS_RESONANCE_FILTER,
	DSP_ADDRESS_MUTE,
	DSP_ADDRESS_GLOBAL_TEMPO,
#ifdef __STEREO_MOD__
	DSP_ADDRESS_INPUT_CONFIG,
#endif
	DSP_NOT_USED = 255
}dsp_module_address_t;

enum
{
	PARAM_EQUAL_POS = 128,
	NOT_SEND_POS = 255
};


typedef void (*setter_handler_t)(uint32_t value);

typedef struct
{
	void* ptr;
	const char* handlerStr;
	dsp_module_address_t dspAddress;
	uint8_t dspPosition;
	const char* name;
	setter_handler_t setterHandler;
}TParamDescriptor;

#endif /* MODULE_PARAMETER_H_ */
