#ifndef SRC_APPLICATION_SYSTEM_H_
#define SRC_APPLICATION_SYSTEM_H_

#include "appdefs.h"

namespace System
{
	enum
	{
		CAB_SIM_DISABLED,
		MIDI_CHANNEL,
		CAB_SIM_CONFIG,
		EXPR_TYPE,

		FSW1_PRESS_TYPE, FSW2_PRESS_TYPE, FSW3_PRESS_TYPE,

		/*calibration*/
		EXPR_CAL_MIN_HI, EXPR_CAL_MIN_LO, EXPR_CAL_MAX_HI, EXPR_CAL_MAX_LO,

		/*preset map to foot press*/
		FSW1_PRESS_PR1, FSW1_PRESS_PR2, FSW1_PRESS_PR3, FSW1_PRESS_PR4,
		FSW2_PRESS_PR1, FSW2_PRESS_PR2, FSW2_PRESS_PR3, FSW2_PRESS_PR4,
		FSW3_PRESS_PR1, FSW3_PRESS_PR2, FSW3_PRESS_PR3, FSW3_PRESS_PR4,

		SPDIF_OUT_TYPE,

		/*num CC to express and foot*/
		EXPR_CCN,
		FSW1_CTRL_PRESS_CC, FSW2_CTRL_PRESS_CC, FSW3_CTRL_PRESS_CC,

		MIDI_PC_IND, /*service*/

		LAST_PRESET_NUM = 31,

		/*FSW button mode*/
		FSW1_MODE = 32, FSW2_MODE, FSW3_MODE,

		FSW1_HOLD_TYPE, FSW2_HOLD_TYPE, FSW3_HOLD_TYPE,

		/*preset map to foot hold*/
		FSW1_HOLD_PR1, FSW1_HOLD_PR2, FSW1_HOLD_PR3, FSW1_HOLD_PR4,
		FSW2_HOLD_PR1, FSW2_HOLD_PR2, FSW2_HOLD_PR3, FSW2_HOLD_PR4,
		FSW3_HOLD_PR1, FSW3_HOLD_PR2, FSW3_HOLD_PR3, FSW3_HOLD_PR4,

		FSW1_CTRL_HOLD_CC, FSW2_CTRL_HOLD_CC, FSW3_CTRL_HOLD_CC,

		TAP_TYPE,
		TUNER_EXTERNAL,
		/*speed foot*/FSW_SPEED,
		TIME_FORMAT,	// Sec, BPM
		TAP_HIGH, /*global temp hi*/
		EXPR_STORE_LEVEL, /*save expression level*/
		SWAP_SWITCH,
		TUNER_SPEED,

		TAP_SCREEN_POPUP,

		MASTER_EQ_ON = 120,
		MASTER_EQ_LOW = 121,
		MASTER_EQ_MID = 122,
		MASTER_EQ_HIGH = 124,

		PHONES_VOLUME = 125,
		MASTER_VOLUME,
		ATTENUATOR,

		MIDI_MAP_START,

		MASTER_EQ_FREQ_VAL_LO = 508,
		MASTER_EQ_FREQ_VAL_HI,

		MASTER_EQ_FREQ_LO = 510,
		MASTER_EQ_FREQ_HI
	};

	typedef enum
	{
		TIME_FORMAT_SEC,
		TIME_FORMAT_BPM
	}TimeFormat;

	typedef enum
	{
		TAP_OFF,
		TAP_RFILTER,
		TAP_DELAY,
		TAP_TREMOLO,
		TAP_GLOBAL
	}TapDestination;

	typedef enum
	{
		TAP_TYPE_PRESET,
		TAP_TYPE_GLOBAL,
		TAP_TYPE_GLOBAL_MIDI
	}TapType;

	typedef enum
	{
		TAP_SCREEN_ON,
		TAP_SCREEN_OFF
	};

	void TapTempo(TapDestination tapDst);
};

extern volatile uint32_t tap_global;
extern volatile uint32_t tap_temp;

#endif /* SRC_APPLICATION_SYSTEM_H_ */
