#ifndef __APPDEFS_H__
#define __APPDEFS_H__

#include "sdk.h"

#include "errno.h"

#define EVENT_BIT_FSTASK_STARTED (1<<0)
#define EVENT_BIT_DSTASK_STARTED (1<<1)
#define EVENT_BIT_IOTASK_STARTED (1<<2)
#define EVENT_BIT_UITASK_STARTED (1<<3)
#define EVENT_BIT_CCTASK_STARTED (1<<4)
#define EVENT_BIT_STTASK_STARTED (1<<5)
#define EVENT_BIT_MDTASK_STARTED (1<<6)
#define EVENT_BIT_SPTASK_STARTED (1<<7)

#define EVENT_ALL_TASK_STARTED ( EVENT_BIT_FSTASK_STARTED | EVENT_BIT_DSTASK_STARTED | EVENT_BIT_IOTASK_STARTED | EVENT_BIT_UITASK_STARTED | EVENT_BIT_CCTASK_STARTED | EVENT_BIT_STTASK_STARTED | EVENT_BIT_MDTASK_STARTED | EVENT_BIT_SPTASK_STARTED )

#endif /*__APPDEFS_H__*/
